/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type CoinStruct = { denom: string; amount: BigNumberish };

export type CoinStructOutput = [denom: string, amount: bigint] & {
  denom: string;
  amount: bigint;
};

export type ICS20AllocationStruct = {
  sourcePort: string;
  sourceChannel: string;
  spendLimit: CoinStruct[];
  allowList: string[];
};

export type ICS20AllocationStructOutput = [
  sourcePort: string,
  sourceChannel: string,
  spendLimit: CoinStructOutput[],
  allowList: string[]
] & {
  sourcePort: string;
  sourceChannel: string;
  spendLimit: CoinStructOutput[];
  allowList: string[];
};

export interface IICS20AuthorizationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "decreaseAllowance"
      | "increaseAllowance"
      | "revoke"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IBCTransferAuthorization"): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, ICS20AllocationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "revoke", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
}

export namespace IBCTransferAuthorizationEvent {
  export type InputTuple = [
    grantee: AddressLike,
    granter: AddressLike,
    allocations: ICS20AllocationStruct[]
  ];
  export type OutputTuple = [
    grantee: string,
    granter: string,
    allocations: ICS20AllocationStructOutput[]
  ];
  export interface OutputObject {
    grantee: string;
    granter: string;
    allocations: ICS20AllocationStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IICS20Authorization extends BaseContract {
  connect(runner?: ContractRunner | null): IICS20Authorization;
  waitForDeployment(): Promise<this>;

  interface: IICS20AuthorizationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [grantee: AddressLike, granter: AddressLike],
    [ICS20AllocationStructOutput[]],
    "view"
  >;

  approve: TypedContractMethod<
    [grantee: AddressLike, allocations: ICS20AllocationStruct[]],
    [boolean],
    "nonpayable"
  >;

  decreaseAllowance: TypedContractMethod<
    [
      grantee: AddressLike,
      sourcePort: string,
      sourceChannel: string,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  increaseAllowance: TypedContractMethod<
    [
      grantee: AddressLike,
      sourcePort: string,
      sourceChannel: string,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  revoke: TypedContractMethod<[grantee: AddressLike], [boolean], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [grantee: AddressLike, granter: AddressLike],
    [ICS20AllocationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [grantee: AddressLike, allocations: ICS20AllocationStruct[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [
      grantee: AddressLike,
      sourcePort: string,
      sourceChannel: string,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [
      grantee: AddressLike,
      sourcePort: string,
      sourceChannel: string,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[grantee: AddressLike], [boolean], "nonpayable">;

  getEvent(
    key: "IBCTransferAuthorization"
  ): TypedContractEvent<
    IBCTransferAuthorizationEvent.InputTuple,
    IBCTransferAuthorizationEvent.OutputTuple,
    IBCTransferAuthorizationEvent.OutputObject
  >;

  filters: {
    "IBCTransferAuthorization(address,address,tuple[])": TypedContractEvent<
      IBCTransferAuthorizationEvent.InputTuple,
      IBCTransferAuthorizationEvent.OutputTuple,
      IBCTransferAuthorizationEvent.OutputObject
    >;
    IBCTransferAuthorization: TypedContractEvent<
      IBCTransferAuthorizationEvent.InputTuple,
      IBCTransferAuthorizationEvent.OutputTuple,
      IBCTransferAuthorizationEvent.OutputObject
    >;
  };
}
