/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICS20I } from "./ICS20I";
export type { IICS20Authorization } from "./IICS20Authorization";
export * as factories from "./factories";
export { ICS20I__factory } from "./factories/ICS20I__factory";
export { IICS20Authorization__factory } from "./factories/IICS20Authorization__factory";
