/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICS20I__factory } from "./ICS20I__factory";
export { IICS20Authorization__factory } from "./IICS20Authorization__factory";
